Update test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,1 +1,46 @@
+ #!/bin/bash
+    ORG_NAME="Somatus-inc" 
 
+    if [ -z "$(TOKEN)" ]; then
+      echo "Error: (TOKEN) environment variable is not set."
+      exit 1
+    fi
+
+  
+    API_URL="https://api.github.com/orgs/${ORG_NAME}/dependabot/alerts"   # GitHub API URL to fetch Dependabot alerts for the organization
+
+    
+    TEMP_FILE="dependabot_alerts.json" # Temporary file to store the JSON response
+    echo "$TEMP_FILE"
+  
+    fetch_dependabot_alerts() {
+      local url=$1
+      curl -s -H "Authorization: token $(TOKEN)" -H "Accept: application/vnd.github+json" "$url" > "$TEMP_FILE"
+    }
+
+    fetch_dependabot_alerts "$API_URL"
+
+    # Check if jq is installed
+    if ! command -v jq &> /dev/null
+    then
+        echo "jq could not be found, please install jq to continue."
+        exit
+    fi
+
+    # Extract alerts and write to CSV file
+    jq -r '.[] | [
+        .repository.name,
+        .number,
+        .security_advisory.severity,
+        .security_advisory.package.name,
+        .security_advisory.summary,
+        .html_url
+    ] | @csv' "$TEMP_FILE" > dependabot_alerts.csv
+
+    # Add header to the CSV file
+    sed -i '1irepository,alert_id,severity,package,summary,url' dependabot_alerts.csv
+
+    # Cleanup
+    rm "$TEMP_FILE"
+
+    echo "Dependabot alerts have been written to dependabot_alerts.csv"
